[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
rtfm-core = { path = "../rtfm-core" }
log = { workspace = true }

[features]
mounts = []
