[package]
name = "output-backends"
version = "0.1.0"
edition = "2021"

[dependencies]
raster = { path = "../raster" }
base64 = "0.22.0"
image = "0.25.1"
ratatui = { workspace = true }
anyhow = "1.0"
sixel-sys = "0.3.1"
